# AWK
[[language]]
name = "awk"
language-servers = ["awk-language-server"]

# Bash
[[language]]
name = "bash"
language-servers = ["bash-language-server"]
auto-format      = true
formatter        = { command = "shfmt", args = ["-i", "4"] }

# C
[[language]]
name = "c"
language-servers = ["clangd"]
auto-format      = true
formatter        = { command = "clang-format", args = ["--style=LLVM"] }

# C#
[[language]]
name = "c-sharp"
language-servers = ["omnisharp"]

# C++
[[language]]
name = "cpp"
language-servers = ["clangd"]
auto-format      = true
formatter        = { command = "clang-format", args = ["--style=LLVM"] }

# CMake
[[language]]
name = "cmake"
language-servers = ["neocmakelsp", "cmake-language-server"]

# CSS
[[language]]
name = "css"
language-servers = ["vscode-css-language-server"]
auto-format      = true

# Docker Compose
[[language]]
name = "docker-compose"

# Dockerfile
[[language]]
name = "dockerfile"
language-servers = ["docker-langserver"]

# Fish
[[language]]
name = "fish"
language-servers = ["fish-lsp"]
auto-format      = true
formatter        = { command = "fish_indent" }

# Go
[[language]]
name = "go"
language-servers = ["gopls"]  
auto-format      = true
formatter        = { command = "goimports" }

# GraphQL
[[language]]
name = "graphql"
language-servers = ["graphql-language-service-cli"]

# HTML
[[language]]
name = "html"
language-servers = ["vscode-html-language-server"]
auto-format      = true
formatter        = { command = "prettier", args = ["--stdin-filepath", "{file}"] }

# Haskell
[[language]]
name = "haskell"
language-servers = ["haskell-language-server"]

# JSON
[[language]]
name = "json"
language-servers = ["vscode-json-language-server"]
auto-format      = true
formatter        = { command = "prettier", args = ["--stdin-filepath", "{file}"] }

# Java
[[language]]
name = "java"
language-servers = ["jdtls"]

# JavaScript
[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]
auto-format      = true
formatter        = { command = "prettier", args = ["--stdin-filepath", "{file}"] }

# Kotlin
[[language]]
name = "kotlin"
language-servers = ["kotlin-language-server"]

# Make
[[language]]
name = "make"
language-servers = []
auto-format      = false

# Markdoc
[[language]]
name = "markdoc"
language-servers = ["markdoc-ls"]

# Markdown
[[language]]
name = "markdown"
language-servers = ["marksman"]
auto-format      = true
formatter        = { command = "prettier", args = ["--stdin-filepath", "{file}"] }

# NASM
[[language]]
name = "nasm"
language-servers = ["asm-lsp"]

# Nix
[[language]]
name = "nix"
language-servers = ["nil", "nixd"]
auto-format      = true
formatter        = { command = "nixpkgs-fmt" }

# PKGBUILD
[[language]]
name = "pkgbuild"

# Perl
[[language]]
name = "perl"
language-servers = ["perlnavigator"]

# Python
[[language]]
name = "python"
language-servers = ["pylsp", "ruff"]
auto-format      = true
formatter        = { command = "black", args = ["-"] }

# Ruby
[[language]]
name = "ruby"
language-servers = ["ruby-lsp", "solargraph"]
auto-format      = true
formatter        = { command = "rubocop", args = ["--stdin", "{file}", "-A", "--stderr"] }

# Rust
[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
auto-format      = true  # rustfmt via rust‑analyzer

# Swift
[[language]]
name = "swift"
language-servers = ["sourcekit-lsp"]
auto-format      = true
formatter        = { command = "swift-format" }

# TOML
[[language]]
name = "toml"
language-servers = ["taplo"]
auto-format      = true

# TypeScript
[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]  # eslint LSP removed
auto-format      = true
formatter        = { command = "prettier", args = ["--stdin-filepath", "{file}"] }

# XML
[[language]]
name = "xml"
language-servers = []
auto-format      = true
formatter        = { command = "xmllint", args = ["--format", "-"] }

# YAML
[[language]]
name = "yaml"
language-servers = ["yaml-language-server", "ansible-language-server"]
auto-format      = true
formatter        = { command = "prettier", args = ["--stdin-filepath", "{file}"] }

# ──────────────────────────
# Language server definitions
# ──────────────────────────

# AWK Language Server
[language-server.awk-language-server]
command = "awk-language-server"

# Ansible Language Server
[language-server.ansible-language-server]
command = "ansible-language-server"
args    = ["--stdio"]

# Assembly LSP (NASM)
[language-server.asm-lsp]
command = "asm-lsp"

# Bash Language Server
[language-server.bash-language-server]
command = "bash-language-server"
args    = ["start"]

# CMake Language Server
[language-server.cmake-language-server]
command = "cmake-language-server"

# Clangd (C/C++)
[language-server.clangd]
command = "clangd"
args    = ["--background-index", "--clang-tidy", "--completion-style=detailed"]

# Django LSP
[language-server.djlsp]
command = "djlsp"

# Docker Language Server
[language-server.docker-langserver]
command = "docker-langserver"
args    = ["--stdio"]

# Fish LSP
[language-server.fish-lsp]
command = "fish-lsp"
args    = ["start"]

# Go Language Server
[language-server.gopls]
command = "gopls"

# GraphQL Language Service
[language-server.graphql-language-service-cli]
command = "graphql-lsp"
args    = ["server", "-m", "stream"]

# Haskell Language Server
[language-server.haskell-language-server]
command = "haskell-language-server-wrapper"
args    = ["--lsp"]

# Java Development Tools Language Server
[language-server.jdtls]
command = "jdtls"

# Kotlin Language Server
[language-server.kotlin-language-server]
command = "kotlin-language-server"

# Markdoc Language Server
[language-server.markdoc-ls]
command = "markdoc-ls"
args    = ["--stdio"]

# Marksman (Markdown)
[language-server.marksman]
command = "marksman"
args    = ["server"]

# Neo CMake LSP
[language-server.neocmakelsp]
command = "neocmakelsp"
args    = ["--stdio"]

# Nix Daemon (nixd)
[language-server.nixd]
command = "nixd"

# Nix Language Server
[language-server.nil]
command = "nil"

# OmniSharp (C#)
[language-server.omnisharp]
command = "omnisharp"
args    = ["--languageserver"]

# Perl Navigator
[language-server.perlnavigator]
command = "perlnavigator"
args    = ["--stdio"]

# Python LSP Server
[language-server.pylsp]
command = "pylsp"

# Ruby LSP
[language-server.ruby-lsp]
command = "ruby-lsp"

# Ruff LSP (Python)
[language-server.ruff]
command = "ruff-lsp"

# Rust Analyzer
[language-server.rust-analyzer]
command = "rust-analyzer"

# Solargraph (Ruby)
[language-server.solargraph]
command = "solargraph"
args    = ["stdio"]

# SourceKit LSP (Swift)
[language-server.sourcekit-lsp]
command = "sourcekit-lsp"

# Taplo (TOML)
[language-server.taplo]
command = "taplo"
args    = ["lsp", "stdio"]

# TypeScript Language Server
[language-server.typescript-language-server]
command = "typescript-language-server"
args    = ["--stdio"]

# VSCode CSS Language Server
[language-server.vscode-css-language-server]
command = "vscode-css-language-server"
args    = ["--stdio"]

# VSCode HTML Language Server
[language-server.vscode-html-language-server]
command = "vscode-html-language-server"
args    = ["--stdio"]

# VSCode JSON Language Server
[language-server.vscode-json-language-server]
command = "vscode-json-language-server"
args    = ["--stdio"]

# YAML Language Server
[language-server.yaml-language-server]
command = "yaml-language-server"
args    = ["--stdio"]
